import Head from "next/head";
import { AuthProvider } from "./context/authClientContext";
import LayoutPages from "./layoutPages";
import "./tailwind.globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./context/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Canal Coca Cola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <LayoutPages>{children}</LayoutPages>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
